# Generated by Django 5.2.11 on 2026-03-03 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_continent_location_continent'),
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('country_iso', models.CharField(default='USA', max_length=10)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StateDataPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('metric', models.CharField(max_length=50)),
                ('value', models.FloatField(blank=True, null=True)),
                ('source', models.CharField(max_length=50)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datapoints', to='api.state')),
            ],
            options={
                'ordering': ['date'],
                'unique_together': {('state', 'date', 'metric', 'source')},
            },
        ),
    ]
