# Generated by Django 5.2.11 on 2026-03-03 16:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_state_statedatapoint'),
    ]

    operations = [
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=160)),
                ('country_name', models.CharField(max_length=100)),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='provinces', to='api.location')),
            ],
            options={
                'ordering': ['country_name', 'name'],
                'unique_together': {('country_name', 'name')},
            },
        ),
        migrations.CreateModel(
            name='ProvinceDataPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('metric', models.CharField(max_length=50)),
                ('value', models.FloatField(blank=True, null=True)),
                ('source', models.CharField(max_length=50)),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datapoints', to='api.province')),
            ],
            options={
                'ordering': ['date'],
                'unique_together': {('province', 'date', 'metric', 'source')},
            },
        ),
    ]
