# Generated by Django 5.2.11 on 2026-03-04 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_province_provincedatapoint'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='datapoint',
            index=models.Index(fields=['metric', 'date', 'location'], name='dp_metric_date_loc_idx'),
        ),
        migrations.AddIndex(
            model_name='datapoint',
            index=models.Index(fields=['location', 'metric', 'date'], name='dp_loc_metric_date_idx'),
        ),
    ]
